CREATE DATABASE IF NOT EXISTS teste_java;


USE teste_java;

CREATE TABLE PEDIDO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO_CONTROLE INT NOT NULL,
    DATA_CADASTRO DATE,
    NOME VARCHAR(255) NOT NULL,
    VALOR DOUBLE NOT NULL,
    QUANTIDADE INT,
    CODIGO_CLIENTE INT NOT NULL,
    DESCONTO DOUBLE DEFAULT 0.0,
    VALOR_TOTAL DOUBLE NOT NULL
);
